server:
  context-path: /quartz-cluster2

  port: 8080

spring:
  application:
    name: quartz-swagger
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 1000
    max-idle: 20
    min-idle: 5
    initial-size: 10
    # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**

mybatis:
  type-aliases-package: com.jjy.quartzjar.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置日志
    map-underscore-to-camel-case: true    # 开启驼峰命名法
    type-aliases-package: com.jjy.quartzjar.entity
  mapper-locations: classpath*:/mybatis/mapper/*.xml


# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: quartz with springfox swagger 3.0
  try-host: http://localhost:${server.port}
